/**
 * Browser certificate administration routes.
 *
 * Browser certs are mTLS client certs issued to humans so they can access the
 * HermitStash web UI when enforceMtls is enabled. They're generated by the
 * same CA that signs sync client certs (lib/mtls-ca.js), packaged as
 * PKCS#12 for one-click install in browsers / OS cert stores, and tracked
 * as rows in the api_keys table so the existing revoke flow cascades to
 * cert_revocations.
 *
 * Storage note: api_keys is reused as the tracking table because its schema
 * already carries the certFingerprint column and hooks the revoke flow. To
 * prevent these rows from being usable as real API keys:
 *   - keyHash is set to "browser:" + sha3Hash(fingerprint). Colon is outside
 *     the Bearer token charset (validateBearerToken), so no incoming Bearer
 *     request could ever hash to this value.
 *   - permissions is empty. Even if a request somehow matched, scope checks fail.
 */
var apiKeysRepo = require("../app/data/repositories/apiKeys.repo");
var { sha3Hash } = require("../lib/crypto");
var { parseJson } = require("../lib/multipart");
var requireAdmin = require("../middleware/require-admin");
var audit = require("../lib/audit");
var mtlsCa = require("../lib/mtls-ca");
var logger = require("../app/shared/logger");

var BROWSER_CERT_PREFIX = "Browser: ";

function isBrowserCertRow(key) {
  return key && typeof key.name === "string" && key.name.indexOf(BROWSER_CERT_PREFIX) === 0;
}

module.exports = function (app) {
  // List browser-cert records. Filtered in JS because name is sealed.
  app.get("/admin/browser-certs/api", function (req, res) {
    if (!requireAdmin(req, res)) return;
    var all = apiKeysRepo.findAll({});
    var browserCerts = all.filter(isBrowserCertRow).map(function (k) {
      return {
        _id: k._id,
        cn: k.name.substring(BROWSER_CERT_PREFIX.length),
        certIssuedAt: k.certIssuedAt || null,
        certExpiresAt: k.certExpiresAt || null,
        certFingerprint: k.certFingerprint || null,
        createdAt: k.createdAt,
      };
    });
    res.json({ certs: browserCerts });
  });

  // Generate a new browser cert and stream the .p12 as a download.
  app.post("/admin/browser-certs/generate", async function (req, res) {
    if (!requireAdmin(req, res)) return;
    try {
      var body = await parseJson(req);
      var cnRaw = String(body.cn || "").trim();
      var password = String(body.password || "");
      var validityDays = parseInt(body.validityDays, 10);
      if (!Number.isInteger(validityDays) || validityDays < 30 || validityDays > 3650) {
        validityDays = 365;
      }

      // CN is baked into the cert and the filename. Keep it to a safe charset
      // and bounded length — the mtls-ca helper re-sanitizes but we reject
      // loudly here so the admin sees the error rather than a mystery rename.
      if (!cnRaw || !/^[A-Za-z0-9][A-Za-z0-9_-]{0,49}$/.test(cnRaw)) {
        return res.status(400).json({ error: "Common Name must be 1–50 chars, alphanumeric + dashes/underscores, starting with alphanumeric." });
      }
      if (password.length < 12) {
        return res.status(400).json({ error: "Password must be at least 12 characters." });
      }

      if (!mtlsCa.caExists()) {
        // Ensure the CA exists before proceeding — first browser cert on a
        // fresh install boots the CA, which is fine but worth logging.
        await mtlsCa.initCA();
      }

      var result = await mtlsCa.generateClientP12(cnRaw, password, validityDays);
      if (!result || !result.p12 || !result.fingerprint256) {
        return res.status(500).json({ error: "Certificate generation failed. Is OpenSSL installed?" });
      }

      // Tracking row in api_keys. keyHash uses a sentinel that can't be
      // produced by any valid Bearer token (colon outside token charset).
      apiKeysRepo.create({
        name: BROWSER_CERT_PREFIX + cnRaw,
        keyHash: "browser:" + sha3Hash(result.fingerprint256),
        prefix: "browser",
        permissions: "", // no scopes — the row is tracking-only
        userId: req.user._id,
        boundStashId: null,
        boundBundleId: null,
        certIssuedAt: result.issuedAt,
        certExpiresAt: result.expiresAt,
        certFingerprint: sha3Hash(result.certPem),
        createdAt: new Date().toISOString(),
      });

      audit.log(audit.ACTIONS.ADMIN_SETTINGS_CHANGED, { details: "Browser certificate issued: " + cnRaw + " (expires " + result.expiresAt + ")", req: req });

      // Stream the .p12 as a download. No JSON envelope — keeps the binary
      // pristine and lets the browser save it directly.
      var safeCn = cnRaw.replace(/[^A-Za-z0-9_-]/g, "");
      var filename = "hermitstash-browser-" + safeCn + ".p12";
      res.writeHead(200, {
        "Content-Type": "application/x-pkcs12",
        "Content-Disposition": 'attachment; filename="' + filename + '"',
        "Content-Length": result.p12.length,
        "Cache-Control": "no-store",
      });
      res.end(result.p12);
    } catch (e) {
      logger.error("Browser cert generate error", { error: e.message || String(e) });
      res.status(500).json({ error: "Failed to generate browser certificate." });
    }
  });
};
