// codebase-patterns:allow-file raw-process-env — reads the MTLS_CA_ALGORITHM boot
//   pin (the same escape hatch lib/mtls-ca.js reads) to suppress the auto-migration.
/**
 * Moves an existing classical sync CA to the post-quantum default at boot.
 *
 * A CA generated by an older build is ECDSA-P384 and keeps that algorithm until
 * something rotates it. This only rotates on a runtime that can VERIFY an
 * ML-DSA client chain in a handshake — being able to issue one is not enough,
 * since the server has to complete mutual auth against it, so the check is a
 * real loopback handshake rather than a capability probe.
 *
 * The rotation retains the superseded CA, so certificates it issued keep
 * verifying while their owners re-enrol, and records a marker for the grace
 * clock — the one piece with no framework primitive behind it, whose retention
 * is open-ended rather than timed. Closing that window drops the retained root
 * and revokes anything still bound to it, through HermitStash's own revocation
 * table: the registry the peer gate actually consults.
 *
 * The browser CA is separate, deliberately classical, and never touched here.
 */
"use strict";

var nodeFs = require("node:fs");
var b = require("./vendor/blamejs");
var C = require("./constants");
var config = require("./config");
var mtlsCa = require("./mtls-ca");
var { revokeCert } = require("./cert-utils");
var apiKeysLazy = b.lazyRequire(function () { return require("../app/data/repositories/apiKeys.repo"); });

// Grace window (days) the superseded CA is retained + its client certs stay
// valid before close-out revokes them. Small integer, not a duration literal.
var GRACE_DAYS = 30;

// The migration target — the sync CA's unpinned post-quantum default. Passed to
// canVerifyInTls() (pre-flight) and rotate() (the algorithm flip).
var TARGET_ALGORITHM = "ML-DSA-87";

/**
 * The algorithm label of the stored sync CA cert in b.mtlsCa's canonical form
 * ("ECDSA-P384-SHA384" / "ML-DSA-87"), or null when there is no CA or the
 * algorithm cannot be determined. Reads mtlsCa.status() — the same cert parse the
 * handle uses — instead of re-parsing the cert here.
 * @returns {string|null}
 */
function storedSyncCaAlgorithm() {
  return mtlsCa.status().algorithm;
}

/**
 * True iff the stored sync CA is a classical elliptic-curve CA (migration
 * candidate). Keys off status().keyType, which stays "ec" even for a non-P384 EC
 * CA whose algorithm label status() reports as null.
 * @returns {boolean}
 */
function isClassicalSyncCa() {
  return mtlsCa.status().keyType === "ec";
}

// Write the grace-clock marker. The retained CA cert (ca.prev.crt) is owned by
// the b.mtlsCa handle — rotate()/commit({retainPrevious}) writes it,
// loadTrustBundle() reads it, dropRetained() removes it. The marker is the one
// artifact with no primitive: b.mtlsCa's retention is open-until-dropRetained
// with no time clock, so HS keeps the 30-day clock + from/to metadata itself.
function _writeMarker(fromGen, fromAlgorithm, now) {
  var marker = {
    startedAt: now,
    fromGen: fromGen,
    toGen: C.CA_GENERATION,
    fromAlgorithm: fromAlgorithm,
    toAlgorithm: TARGET_ALGORITHM,
    graceDays: GRACE_DAYS,
  };
  b.atomicFile.writeSync(C.PATHS.CA_MIGRATION_MARKER, Buffer.from(JSON.stringify(marker)), { fileMode: 0o644 });
}

/**
 * Open a grace CLOCK for an admin-triggered rotation: write the marker
 * describing the outgoing CA. The retention itself (ca.prev.crt) is done by the
 * caller's commit({ retainPrevious: true }); this only records the 30-day clock
 * + from/to metadata b.mtlsCa has no primitive for. Reads the CURRENT (outgoing)
 * CA via status(), so it MUST run before the caller commits the replacement.
 * @param {{ now?: number }} [opts]
 * @returns {{started: boolean, reason?: string, fromGen?: number, fromAlgorithm?: string, graceDays?: number}}
 */
function beginGrace(opts) {
  opts = opts || {};
  var now = typeof opts.now === "number" ? opts.now : Date.now();
  var status = mtlsCa.status();
  if (!status.exists) return { started: false, reason: "no-ca" };
  _writeMarker(status.generation, status.algorithm, now);
  return { started: true, fromGen: status.generation, fromAlgorithm: status.algorithm, graceDays: GRACE_DAYS };
}

function _readMarker() {
  try {
    if (!nodeFs.existsSync(C.PATHS.CA_MIGRATION_MARKER)) return null;
    var raw = nodeFs.readFileSync(C.PATHS.CA_MIGRATION_MARKER, "utf8");
    return b.safeJson.parseOrDefault(raw, null);
  } catch (_e) {
    return null;
  }
}

/**
 * True iff a migration marker exists and its grace window is still open.
 * @returns {boolean}
 */
function graceActive() {
  var marker = _readMarker();
  if (!marker || typeof marker.startedAt !== "number") return false;
  return Date.now() < marker.startedAt + C.TIME.days(marker.graceDays || GRACE_DAYS);
}

/**
 * Milliseconds remaining in the grace window, or 0 when no window is open.
 * @returns {number}
 */
function graceRemainingMs() {
  var marker = _readMarker();
  if (!marker || typeof marker.startedAt !== "number") return 0;
  var end = marker.startedAt + C.TIME.days(marker.graceDays || GRACE_DAYS);
  var left = end - Date.now();
  return left > 0 ? left : 0;
}

// Revoke every SYNC client cert issued before this migration's marker.startedAt
// — i.e. by the superseded classical CA. Browser certs are signed by the SEPARATE,
// unmigrated classical browser CA and are excluded (same keyHash discriminant
// the admin regen path uses). Revocation goes through HS cert_revocations so
// the mTLS peer gate (cert-utils.isPeerCertRevoked) rejects them — blamejs's own
// revokeGeneration()/CRL target a ledger HS neither populates nor consults.
function _revokeOldGenSyncCerts(startedAt) {
  var revoked = 0;
  try {
    var apiKeysRepo = apiKeysLazy();
    var keys = apiKeysRepo.findAll().filter(function (k) { return k && k.certFingerprint; });
    for (var i = 0; i < keys.length; i++) {
      var k = keys[i];
      if ((k.keyHash || "").indexOf("browser:") === 0) continue;
      if (!k.certIssuedAt) continue;
      if (new Date(k.certIssuedAt).getTime() >= startedAt) continue;
      if (revokeCert(k.certFingerprint, k.prefix || "", "sync CA migration grace closed")) revoked++;
    }
  } catch (_e) { /* revocation is best-effort; a partial sweep re-runs next boot / daily job */ }
  return revoked;
}

/**
 * Run the sync-CA PQC migration once, at boot. No-op unless ALL guards hold:
 * a classical sync CA exists, it is not operator-provided, no MTLS_CA_ALGORITHM
 * pin, MTLS_AUTO_MIGRATE is not false, and the runtime can verify ML-DSA in TLS.
 * @param {{ log?: function, now?: number }} [opts]
 * @returns {Promise<{migrated: boolean, reason?: string}>}
 */
async function maybeMigrate(opts) {
  opts = opts || {};
  var log = typeof opts.log === "function" ? opts.log : function () {};
  var now = typeof opts.now === "number" ? opts.now : Date.now();

  var status = mtlsCa.status();
  if (!status.exists) return { migrated: false, reason: "no-ca" };
  if (status.keyType !== "ec") return { migrated: false, reason: "already-pqc" };
  // An operator who supplies the CA via MTLS_CA_KEY / MTLS_CA_CERT (for example a
  // CA mounted read-only from a secret volume, or one an external tool manages)
  // owns its lifecycle. Auto-migration manages ONLY HS's own default-path CA and
  // must never rotate an operator-provided one — doing so would overwrite the
  // operator's chosen CA (or fail on a read-only mount). Such an operator pins the
  // algorithm explicitly (or rotates the CA themselves) to change it.
  if (process.env.MTLS_CA_KEY || process.env.MTLS_CA_CERT) {
    return { migrated: false, reason: "operator-provided-ca" };
  }
  if (process.env.MTLS_CA_ALGORITHM) return { migrated: false, reason: "pinned" };
  if (config.mtlsAutoMigrate === false) return { migrated: false, reason: "auto-migrate-off" };
  var capable = await mtlsCa.canVerifyInTls(TARGET_ALGORITHM);
  if (!capable) return { migrated: false, reason: "capability-not-met" };

  var fromAlgorithm = status.algorithm;
  var fromGen = status.generation;

  // rotate() generates a fresh CA under the target algorithm, atomically commits
  // it (the singleton reloads and issues PQC afterward), and snapshots the
  // outgoing CA to ca.prev.crt — all under the CA lock, crash-safe, with its own
  // rollback journal. Replaces the old generateCa + hand-written ca.prev.crt +
  // bare commit + manual rollback dance. The explicit algorithm overrides
  // rotate()'s default algorithm-preservation to flip classical -> PQC.
  var rotated = await mtlsCa.rotate({
    generation: C.CA_GENERATION,
    algorithm: TARGET_ALGORITHM,
    retainPrevious: true,
  });

  // Record the grace clock AFTER the rotation commits, so a rotate failure leaves
  // no phantom marker. A marker-write failure after a committed rotation degrades
  // safe: the retained CA simply stays trusted (over-trust) until a later close-
  // out with a restored clock, never dropping an in-flight cert.
  _writeMarker(fromGen, fromAlgorithm, now);

  log("sync CA migrated " + fromAlgorithm + " -> " + rotated.algorithm + " (generation " + fromGen + " -> " + rotated.generation + "); previous CA retained " + GRACE_DAYS + "d for in-flight sync certs.");
  return {
    migrated: true,
    fromAlgorithm: fromAlgorithm,
    toAlgorithm: rotated.algorithm,
    fromGen: fromGen,
    toGen: rotated.generation,
    graceDays: GRACE_DAYS,
  };
}

/**
 * Close out an expired grace window: drop the retained previous CA, revoke any
 * sync client cert still bound to it, and delete the marker. No-op while the
 * window is open or when there is no marker. Idempotent — safe to call at boot
 * and on the daily cert-expiry job.
 * @param {{ log?: function }} [opts]
 * @returns {Promise<{closed: boolean, reason?: string, revoked?: number}>}
 */
async function closeOutGraceIfExpired(opts) {
  opts = opts || {};
  var log = typeof opts.log === "function" ? opts.log : function () {};
  var marker = _readMarker();
  if (!marker || typeof marker.startedAt !== "number") return { closed: false, reason: "no-marker" };
  if (graceActive()) return { closed: false, reason: "grace-active" };

  // dropRetained() removes the retained ca.prev.crt under the CA lock and
  // reconciles a crashed rotation's journal — strictly safer than a raw unlink,
  // and the file it owns is the same ca.prev.crt the trust bundle served.
  try { await mtlsCa.dropRetained(); } catch (_e) { /* best-effort; retries next boot / daily job */ }
  var revoked = _revokeOldGenSyncCerts(marker.startedAt);
  try { if (nodeFs.existsSync(C.PATHS.CA_MIGRATION_MARKER)) nodeFs.unlinkSync(C.PATHS.CA_MIGRATION_MARKER); } catch (_e) { /* best-effort */ }

  log("sync-CA migration grace closed; dropped retained previous CA and revoked " + revoked + " superseded client cert(s).");
  return { closed: true, revoked: revoked };
}

/**
 * Boot-time entry: run the migration + grace close-out and emit a clear operator
 * banner. Called from server.js's async boot() BEFORE server-main builds its TLS
 * trust bundle, so a migrated ML-DSA-87 CA (and the retained previous CA) are on
 * disk before the live TLS `ca` bundle is read — new PQC client certs verify in
 * the SAME process, and existing sync certs keep working via the retained root.
 * Never throws (a probe/rotate failure degrades to a logged warning).
 * @param {{ log?: function }} [opts]
 * @returns {Promise<object>} the maybeMigrate result
 */
async function runBootMigration(opts) {
  opts = opts || {};
  var log = typeof opts.log === "function" ? opts.log : function () {};
  var migResult = { migrated: false, reason: "error" };
  try {
    migResult = await maybeMigrate({ log: log });
    await closeOutGraceIfExpired({ log: log });
  } catch (e) {
    log("mTLS sync-CA migration check failed (non-fatal): " + (e && e.message ? e.message : String(e)));
    return migResult;
  }

  if (migResult.migrated) {
    log("mTLS sync CA auto-migrated to ML-DSA-87 (PQC). The previous CA is trusted for " +
      (migResult.graceDays || GRACE_DAYS) + " more days so existing sync clients keep connecting — have them re-enroll within the window.");
  } else if (migResult.reason === "pinned") {
    log("mTLS sync-CA PQC migration suppressed by MTLS_CA_ALGORITHM pin — the sync CA stays on its pinned algorithm.");
  } else if (migResult.reason === "operator-provided-ca") {
    log("mTLS sync-CA PQC migration skipped — the CA is operator-provided (MTLS_CA_KEY / MTLS_CA_CERT); its lifecycle is yours to manage.");
  } else if (migResult.reason === "auto-migrate-off") {
    log("mTLS sync-CA PQC migration disabled (MTLS_AUTO_MIGRATE=false) — an existing classical sync CA is left in place.");
  } else if (migResult.reason === "capability-not-met") {
    log("mTLS sync-CA PQC migration deferred — this runtime cannot verify ML-DSA in a TLS handshake (needs OpenSSL >= 3.5). The classical sync CA is retained.");
  }

  try {
    if (graceActive()) {
      var daysLeft = Math.ceil(graceRemainingMs() / C.TIME.days(1));
      log("mTLS sync-CA migration grace active — previous CA trusted for ~" + daysLeft + " more day(s); superseded sync certs are revoked at close-out.");
    }
  } catch (_e) { /* grace probe best-effort */ }

  if (!migResult.migrated) {
    try {
      var caStatus = mtlsCa.status();
      if (caStatus.exists && caStatus.isLegacy) {
        log("mTLS CA is a legacy generation (v" + caStatus.generation + " -> current v" + caStatus.current +
          "). Regenerate via Admin -> General -> Danger Zone to pick up the upgraded algorithm envelope.");
      }
    } catch (_e) { /* mtls-ca not loaded — non-fatal */ }
  }
  return migResult;
}

module.exports = {
  storedSyncCaAlgorithm: storedSyncCaAlgorithm,
  isClassicalSyncCa: isClassicalSyncCa,
  maybeMigrate: maybeMigrate,
  runBootMigration: runBootMigration,
  beginGrace: beginGrace,
  graceActive: graceActive,
  graceRemainingMs: graceRemainingMs,
  closeOutGraceIfExpired: closeOutGraceIfExpired,
};
